name: DeployAPI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v1

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build AvenSellWebApi\AvenSellWebApi.csproj --configuration Release

    - name: Project publish
      run: dotnet publish -c Release AvenSellWebApi\AvenSellWebApi.csproj -o ${{env.DOTNET_ROOT}}/AvenSellWebApi

    - name: Deploy to IIS
      run: |
        if ((Get-WebSiteState -Name avensell-generic-back-end).Value -eq "Started")
        {
            Stop-WebSite -Name avensell-generic-back-end
            echo "Stopped Website avensell-generic-back-end"
        }
        if ((Get-WebAppPoolState -Name avensell-generic-back-end).Value -eq "Started")
        {
            Stop-WebAppPool -Name avensell-generic-back-end
            echo "Stopped Application Pool avensell-generic-back-end"
        }
        
        Start-Sleep -s 15        
        Copy-Item ${{env.DOTNET_ROOT}}/WebApi/* C:\inetpub\wwwroot\sites\avensellGeneric -Recurse -Force
        
        if ((Get-WebSiteState -Name avensell-generic-back-end).Value -eq "Stopped")
        {
            Start-WebSite -Name avensell-generic-back-end
            echo "Started Website avensell-generic-back-end"
        }
        if ((Get-WebAppPoolState -Name avensell-generic-back-end).Value -eq "Stopped")
        {
            Start-WebAppPool -Name avensell-generic-back-end
            echo "Started Application Pool avensell-generic-back-end"
        }
        
        if ($lastexitcode -lt 8) { $global:lastexitcode = 0 }
